# logger path (default is .)
log_path: ./log.log

device_1:
  # device config defaults
  ip: '' # internal ip address
  dev_id: '' # device uuid
  ver: '' # protocol version (3.1 or 3.3)
  loc_key: '' # local encryption key
  screen_rel: 'DP-0' # what screen this light represents
  name: 'LEFT_REL_LIGHT'

device_2:
  # device config defaults
  ip: '' # internal ip address
  dev_id: '' # device uuid
  ver: '' # protocol version (3.1 or 3.3)
  loc_key: '' # local encryption key
  screen_rel: 'DP-1' # what screen this light represents
  name: 'CNTR_REL_LIGHT'

device_2:
  # device config defaults
  ip: '' # internal ip address
  dev_id: '' # device uuid
  ver: '' # protocol version (3.1 or 3.3)
  loc_key: '' # local encryption key
  screen_rel: 'DP-2' # what screen this light represents
  name: 'RGHT_REL_LIGHT'

debug: false
verbose: false
log: true
cloud: false
default_rgb_val: '123,123,123'
 

